version: '3.8'
services:
  server:
    restart: unless-stopped
    build: .
    init: true
    user: '1000:1000'
    ports:
      - 127.0.0.1:21001:21001
      - 127.0.0.1:9229:9229
    command:
      - bash
      - '-c'
      - 'node --inspect=0.0.0.0 src/index.js'
    volumes:
      - ./.env:/usr/src/app/.env
      - ./.data:/usr/src/app/.data
      - ./src:/usr/src/app/src
      - ./lib:/usr/src/app/lib
      - ./data:/usr/src/app/data
      - ./secrets.js:/usr/src/app/secrets.js
