name: Update stats
on:
  schedule:
    - cron: '0 0/6 * * *'
  workflow_dispatch: {}
jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn
      - run: node .github/actions/update-stats
        env:
          BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          NOTES_API_PREFIX: ${{ secrets.NOTES_API_PREFIX }}
